devices:
  - ip: "192.168.239.134"
    port: 30001
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname Stockholm"
        - "interface e0/0"
        - "ip address 192.168.1.1 255.255.255.0"
        - "no shutdown"
        - "interface s2/0"
        - "ip address 10.10.10.1 255.255.255.252"
        - "no shutdown"
        - "interface s2/1"
        - "ip address 10.10.10.9 255.255.255.252"
        - "no shutdown"
        - "ip dhcp pool Stockholm"
        - "network 192.168.1.0 255.255.255.0"
        - "default-router 192.168.1.1"
        - "dns-server 192.168.1.254"
        - "domain-name firma.se"
        - "ip dhcp excluded-address 192.168.1.254"
        - "ip dhcp excluded-address 192.168.1.253"
        - "router rip"
        - "version 2"
        - "network 192.168.1.0"
        - "network 10.10.10.0" 
        - "default-information originate"
        - "no auto-summary"
        - "ip route 0.0.0.0 0.0.0.0 10.10.10.10"        
      show:
        - "show ip interface brief"
        - "show ip route"
  - ip: "192.168.239.134"
    port: 30002
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname goteborg"
        - "interface s2/0"
        - "ip address 10.10.10.2 255.255.255.252"
        - "no shutdown"
        - "interface e0/0"
        - "ip address 192.168.2.1 255.255.255.0"
        - "no shutdown"
        - "ip dhcp pool goteborg"
        - "network 192.168.2.0 255.255.255.0"
        - "default-router 192.168.2.1"
        - "dns-server 192.168.1.254"
        - "router rip"
        - "version 2"
        - "network 192.168.2.0"
        - "network 10.10.10.0"
        - "no auto-summary"
      show:
        - "show ip interface brief"
        - "show ip route"
  - ip: "192.168.239.134"
    port: 30003
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname malmo"
        - "interface s2/1"
        - "ip address 10.10.10.10 255.255.255.252"
        - "no shutdown"
        - "interface e0/0"
        - "ip address 192.168.3.1 255.255.255.0"
        - "no shutdown"
        - "ip dhcp pool malmo"
        - "network 192.168.3.0 255.255.255.0"
        - "default-router 192.168.3.1"
        - "dns-server 192.168.1.254"
        - "ip route 0.0.0.0 0.0.0.0 10.10.10.9"