devices:
  - ip: "192.168.239.134"
    port: 30001
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname Stockholm"
        - "ip dhcp pool Stockholm"
        - "network 192.168.10.0 255.255.255.0"
        - "default-router 192.168.10.1"
        - "dns-server 192.168.10.254"
        - "domain-name firma.se"
        - "interface E0/0"
        - "ip address 192.168.10.1 255.255.255.0"
        - "speed 100"
        - "duplex full"
        - "no shutdown"
        - "interface Serial1/0"
        - "ip address 10.0.12.1 255.255.255.252"
        - "no shutdown"
        - "interface Serial1/1"
        - "ip address 10.0.13.1 255.255.255.252"
        - "no shutdown"
        - "router rip"
        - "version 2"
        - "network 192.168.10.0"
        - "default-information originate"
        - "no auto-summary"
        - "ip route 192.168.20.0 255.255.255.0 10.0.12.2"
        - "ip route 192.168.30.0 255.255.255.0 10.0.13.2"
      show: []
  - ip: "192.168.239.134"
    port: 30002
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname Goteboer"
        - "ip dhcp pool Goteboer"
        - "network 192.168.2.0 255.255.255.0"
        - "default-router 192.168.2.1"
        - "dns-server 192.168.1.254"
        - "interface e0/0"
        - "ip address 192.168.2.1 255.255.255.0"
        - "speed 100"
        - "duplex full"
        - "no shutdown"
        - "interface Serial1/0"
        - "ip address 10.10.10.2 255.255.255.252"
        - "clock rate 64000"
        - "no shutdown"
        - "no shutdown"
        - "ip classless"
        - "ip route 0.0.0.0 0.0.0.0 10.10.10.1"
        - "end"
      show: []
  - ip: "192.168.239.134"
    port: 30003
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname Malmo"
        - "ip dhcp pool Malmo"
        - "network 192.168.3.0 255.255.255.0"
        - "default-router 192.168.3.1"
        - "dns-server 192.168.1.254"
        - "interface e0/0"
        - "ip address 192.168.3.1 255.255.255.0"
        - "speed 100"
        - "duplex full"
        - "no shutdown"
        - "interface Serial1/0"
        - "ip address 10.10.10.10 255.255.255.252"
        - "clock rate 64000"
        - "no shutdown"
        - "ip route 0.0.0.0 0.0.0.0 10.10.10.9"
      show: []