devices:
  - ip: 192.168.0.81
    port: 300010
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 15.0
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Switch
        - spanning-tree mode pvst
        - spanning-tree extend system-id
        - interface FastEthernet0/1
        - switchport access vlan 50
        - interface FastEthernet0/2
        - switchport access vlan 50
        - interface FastEthernet0/3
        - switchport mode trunk
        - interface FastEthernet0/4
        - interface FastEthernet0/5
        - interface FastEthernet0/6
        - interface FastEthernet0/7
        - interface FastEthernet0/8
        - interface FastEthernet0/9
        - interface FastEthernet0/10
        - interface FastEthernet0/11
        - interface FastEthernet0/12
        - interface FastEthernet0/13
        - interface FastEthernet0/14
        - interface FastEthernet0/15
        - interface FastEthernet0/16
        - interface FastEthernet0/17
        - interface FastEthernet0/18
        - interface FastEthernet0/19
        - interface FastEthernet0/20
        - interface FastEthernet0/21
        - interface FastEthernet0/22
        - interface FastEthernet0/23
        - interface FastEthernet0/24
        - interface GigabitEthernet0/1
        - interface GigabitEthernet0/2
        - interface Vlan1
        - no ip address
        - shutdown
        - line con 0
        - line vty 0 4
        - login
        - line vty 5 15
        - login
        - end
      show: []
  - ip: 192.168.0.81
    port: 30001
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 12.2(37)SE1
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Switch
        - ip dhcp excluded-address 192.168.30.254
        - ip dhcp excluded-address 192.168.40.254
        - ip dhcp pool VLAN30
        - network 192.168.30.0 255.255.255.0
        - default-router 192.168.30.254
        - dns-server 192.168.50.1
        - ip dhcp pool VLAN40
        - network 192.168.40.0 255.255.255.0
        - default-router 192.168.40.254
        - dns-server 192.168.50.1
        - ip routing
        - spanning-tree mode pvst
        - interface FastEthernet0/1
        - interface FastEthernet0/2
        - interface FastEthernet0/3
        - no switchport
        - ip address 192.168.2.1 255.255.255.252
        - duplex auto
        - speed auto
        - interface FastEthernet0/4
        - interface FastEthernet0/5
        - interface FastEthernet0/6
        - interface FastEthernet0/7
        - interface FastEthernet0/8
        - interface FastEthernet0/9
        - interface FastEthernet0/10
        - interface FastEthernet0/11
        - interface FastEthernet0/12
        - interface FastEthernet0/13
        - interface FastEthernet0/14
        - interface FastEthernet0/15
        - interface FastEthernet0/16
        - interface FastEthernet0/17
        - interface FastEthernet0/18
        - interface FastEthernet0/19
        - interface FastEthernet0/20
        - interface FastEthernet0/21
        - interface FastEthernet0/22
        - interface FastEthernet0/23
        - interface FastEthernet0/24
        - interface GigabitEthernet0/1
        - interface GigabitEthernet0/2
        - interface Vlan1
        - no ip address
        - shutdown
        - interface Vlan30
        - mac-address 00d0.971c.5b01
        - ip address 192.168.30.254 255.255.255.0
        - interface Vlan40
        - mac-address 00d0.971c.5b02
        - ip address 192.168.40.254 255.255.255.0
        - router rip
        - version 2
        - network 192.168.2.0
        - network 192.168.30.0
        - network 192.168.40.0
        - no auto-summary
        - ip classless
        - ip route 0.0.0.0 0.0.0.0 192.168.2.2
        - ip flow-export version 9
        - no cdp run
        - line con 0
        - line aux 0
        - line vty 0 4
        - login
        - end
      show: []
  - ip: 192.168.0.81
    port: 30002
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 12.2(37)SE1
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Switch
        - ip routing
        - spanning-tree mode pvst
        - interface FastEthernet0/1
        - no switchport
        - ip address 192.168.1.2 255.255.255.252
        - duplex auto
        - speed auto
        - interface FastEthernet0/2
        - no switchport
        - ip address 192.168.2.2 255.255.255.252
        - duplex auto
        - speed auto
        - interface FastEthernet0/3
        - interface FastEthernet0/4
        - no switchport
        - ip address 192.168.3.1 255.255.255.252
        - duplex auto
        - speed auto
        - interface FastEthernet0/5
        - interface FastEthernet0/6
        - interface FastEthernet0/7
        - interface FastEthernet0/8
        - interface FastEthernet0/9
        - interface FastEthernet0/10
        - interface FastEthernet0/11
        - interface FastEthernet0/12
        - interface FastEthernet0/13
        - interface FastEthernet0/14
        - interface FastEthernet0/15
        - interface FastEthernet0/16
        - interface FastEthernet0/17
        - interface FastEthernet0/18
        - interface FastEthernet0/19
        - interface FastEthernet0/20
        - interface FastEthernet0/21
        - interface FastEthernet0/22
        - interface FastEthernet0/23
        - interface FastEthernet0/24
        - interface GigabitEthernet0/1
        - interface GigabitEthernet0/2
        - interface Vlan1
        - no ip address
        - shutdown
        - interface Vlan50
        - mac-address 0040.0b82.8a01
        - ip address 192.168.50.254 255.255.255.0
        - router rip
        - version 2
        - network 192.168.1.0
        - network 192.168.2.0
        - network 192.168.3.0
        - network 192.168.50.0
        - no auto-summary
        - ip classless
        - ip route 0.0.0.0 0.0.0.0 192.168.3.2
        - ip flow-export version 9
        - no cdp run
        - line con 0
        - line aux 0
        - line vty 0 4
        - login
        - end
      show: []
  - ip: 192.168.0.81
    port: 30003
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 12.2(37)SE1
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Switch
        - ip dhcp excluded-address 192.168.10.254
        - ip dhcp excluded-address 192.168.20.254
        - ip dhcp pool VLAN10
        - network 192.168.10.0 255.255.255.0
        - default-router 192.168.10.254
        - dns-server 192.168.50.1
        - ip dhcp pool VLAN20
        - network 192.168.20.0 255.255.255.0
        - default-router 192.168.20.254
        - dns-server 192.168.50.1
        - ip routing
        - spanning-tree mode pvst
        - interface FastEthernet0/1
        - interface FastEthernet0/2
        - interface FastEthernet0/3
        - no switchport
        - ip address 192.168.1.1 255.255.255.252
        - duplex auto
        - speed auto
        - interface FastEthernet0/4
        - interface FastEthernet0/5
        - interface FastEthernet0/6
        - interface FastEthernet0/7
        - interface FastEthernet0/8
        - interface FastEthernet0/9
        - interface FastEthernet0/10
        - interface FastEthernet0/11
        - interface FastEthernet0/12
        - interface FastEthernet0/13
        - interface FastEthernet0/14
        - interface FastEthernet0/15
        - interface FastEthernet0/16
        - interface FastEthernet0/17
        - interface FastEthernet0/18
        - interface FastEthernet0/19
        - interface FastEthernet0/20
        - interface FastEthernet0/21
        - interface FastEthernet0/22
        - interface FastEthernet0/23
        - interface FastEthernet0/24
        - interface GigabitEthernet0/1
        - interface GigabitEthernet0/2
        - interface Vlan1
        - no ip address
        - shutdown
        - interface Vlan10
        - mac-address 0002.1753.a901
        - ip address 192.168.10.254 255.255.255.0
        - interface Vlan20
        - mac-address 0002.1753.a902
        - ip address 192.168.20.254 255.255.255.0
        - router rip
        - version 2
        - network 192.168.1.0
        - network 192.168.10.0
        - network 192.168.20.0
        - no auto-summary
        - ip classless
        - ip route 0.0.0.0 0.0.0.0 192.168.1.2
        - ip flow-export version 9
        - no cdp run
        - line con 0
        - line aux 0
        - line vty 0 4
        - login
        - end
      show: []
  - ip: 192.168.0.81
    port: 30004
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 15.1
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Router
        - no ip cef
        - no ipv6 cef
        - license udi pid CISCO1941/K9 sn FTX1524PAQM-
        - spanning-tree mode pvst
        - interface GigabitEthernet0/0
        - ip address 192.168.3.2 255.255.255.252
        - ip nat inside
        - duplex auto
        - speed auto
        - interface GigabitEthernet0/1
        - no ip address
        - duplex auto
        - speed auto
        - shutdown
        - interface Serial0/0/0
        - ip address 200.1.1.1 255.255.255.252
        - ip nat outside
        - interface Serial0/0/1
        - no ip address
        - clock rate 2000000
        - shutdown
        - interface Vlan1
        - no ip address
        - shutdown
        - router rip
        - version 2
        - network 192.168.3.0
        - network 200.1.1.0
        - no auto-summary
        - ip nat pool napt-pool 200.1.1.1 200.1.1.1 netmask 255.255.255.252
        - ip nat inside source list 1 pool napt-pool overload
        - ip classless
        - ip route 0.0.0.0 0.0.0.0 200.1.1.2
        - ip flow-export version 9
        - access-list 1 permit 192.168.10.0 0.0.0.255
        - access-list 1 permit 192.168.20.0 0.0.0.255
        - access-list 1 permit 192.168.30.0 0.0.0.255
        - access-list 1 permit 192.168.40.0 0.0.0.255
        - no cdp run
        - line con 0
        - line aux 0
        - line vty 0 4
        - login
        - end
      show: []
  - ip: 192.168.0.81
    port: 30005
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 15.1
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Router
        - no ip cef
        - no ipv6 cef
        - license udi pid CISCO1941/K9 sn FTX15249K63-
        - spanning-tree mode pvst
        - interface GigabitEthernet0/0
        - ip address 218.75.230.254 255.255.255.0
        - duplex auto
        - speed auto
        - interface GigabitEthernet0/1
        - no ip address
        - duplex auto
        - speed auto
        - shutdown
        - interface Serial0/0/0
        - ip address 200.1.1.2 255.255.255.252
        - clock rate 2000000
        - interface Serial0/0/1
        - no ip address
        - clock rate 2000000
        - shutdown
        - interface Vlan1
        - no ip address
        - shutdown
        - ip classless
        - ip flow-export version 9
        - no cdp run
        - line con 0
        - line aux 0
        - line vty 0 4
        - login
        - end
      show: []
  - ip: 192.168.0.81
    port: 30006
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 15.0
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Switch
        - spanning-tree mode pvst
        - spanning-tree extend system-id
        - interface FastEthernet0/1
        - switchport access vlan 10
        - interface FastEthernet0/2
        - switchport access vlan 10
        - interface FastEthernet0/3
        - switchport mode trunk
        - interface FastEthernet0/4
        - interface FastEthernet0/5
        - interface FastEthernet0/6
        - interface FastEthernet0/7
        - interface FastEthernet0/8
        - interface FastEthernet0/9
        - interface FastEthernet0/10
        - interface FastEthernet0/11
        - interface FastEthernet0/12
        - interface FastEthernet0/13
        - interface FastEthernet0/14
        - interface FastEthernet0/15
        - interface FastEthernet0/16
        - interface FastEthernet0/17
        - interface FastEthernet0/18
        - interface FastEthernet0/19
        - interface FastEthernet0/20
        - interface FastEthernet0/21
        - interface FastEthernet0/22
        - interface FastEthernet0/23
        - interface FastEthernet0/24
        - interface GigabitEthernet0/1
        - interface GigabitEthernet0/2
        - interface Vlan1
        - no ip address
        - shutdown
        - line con 0
        - line vty 0 4
        - login
        - line vty 5 15
        - login
        - end
      show: []
  - ip: 192.168.0.81
    port: 30007
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 15.0
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Switch
        - spanning-tree mode pvst
        - spanning-tree extend system-id
        - interface FastEthernet0/1
        - switchport access vlan 20
        - interface FastEthernet0/2
        - switchport access vlan 20
        - interface FastEthernet0/3
        - switchport mode trunk
        - interface FastEthernet0/4
        - interface FastEthernet0/5
        - interface FastEthernet0/6
        - interface FastEthernet0/7
        - interface FastEthernet0/8
        - interface FastEthernet0/9
        - interface FastEthernet0/10
        - interface FastEthernet0/11
        - interface FastEthernet0/12
        - interface FastEthernet0/13
        - interface FastEthernet0/14
        - interface FastEthernet0/15
        - interface FastEthernet0/16
        - interface FastEthernet0/17
        - interface FastEthernet0/18
        - interface FastEthernet0/19
        - interface FastEthernet0/20
        - interface FastEthernet0/21
        - interface FastEthernet0/22
        - interface FastEthernet0/23
        - interface FastEthernet0/24
        - interface GigabitEthernet0/1
        - interface GigabitEthernet0/2
        - interface Vlan1
        - no ip address
        - shutdown
        - line con 0
        - line vty 0 4
        - login
        - line vty 5 15
        - login
        - end
      show: []
  - ip: 192.168.0.81
    port: 30008
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 15.0
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Switch
        - spanning-tree mode pvst
        - spanning-tree extend system-id
        - interface FastEthernet0/1
        - switchport access vlan 30
        - interface FastEthernet0/2
        - switchport access vlan 30
        - interface FastEthernet0/3
        - switchport mode trunk
        - interface FastEthernet0/4
        - interface FastEthernet0/5
        - interface FastEthernet0/6
        - interface FastEthernet0/7
        - interface FastEthernet0/8
        - interface FastEthernet0/9
        - interface FastEthernet0/10
        - interface FastEthernet0/11
        - interface FastEthernet0/12
        - interface FastEthernet0/13
        - interface FastEthernet0/14
        - interface FastEthernet0/15
        - interface FastEthernet0/16
        - interface FastEthernet0/17
        - interface FastEthernet0/18
        - interface FastEthernet0/19
        - interface FastEthernet0/20
        - interface FastEthernet0/21
        - interface FastEthernet0/22
        - interface FastEthernet0/23
        - interface FastEthernet0/24
        - interface GigabitEthernet0/1
        - interface GigabitEthernet0/2
        - interface Vlan1
        - no ip address
        - shutdown
        - line con 0
        - line vty 0 4
        - login
        - line vty 5 15
        - login
        - end
      show: []
  - ip: 192.168.0.81
    port: 30009
    username: admin
    password: admin
    device_type: cisco_ios_telnet
    commands:
      config:
        - version 15.0
        - no service timestamps log datetime msec
        - no service timestamps debug datetime msec
        - no service password-encryption
        - hostname Switch
        - spanning-tree mode pvst
        - spanning-tree extend system-id
        - interface FastEthernet0/1
        - switchport access vlan 40
        - interface FastEthernet0/2
        - switchport access vlan 40
        - interface FastEthernet0/3
        - switchport mode trunk
        - interface FastEthernet0/4
        - interface FastEthernet0/5
        - interface FastEthernet0/6
        - interface FastEthernet0/7
        - interface FastEthernet0/8
        - interface FastEthernet0/9
        - interface FastEthernet0/10
        - interface FastEthernet0/11
        - interface FastEthernet0/12
        - interface FastEthernet0/13
        - interface FastEthernet0/14
        - interface FastEthernet0/15
        - interface FastEthernet0/16
        - interface FastEthernet0/17
        - interface FastEthernet0/18
        - interface FastEthernet0/19
        - interface FastEthernet0/20
        - interface FastEthernet0/21
        - interface FastEthernet0/22
        - interface FastEthernet0/23
        - interface FastEthernet0/24
        - interface GigabitEthernet0/1
        - interface GigabitEthernet0/2
        - interface Vlan1
        - no ip address
        - shutdown
        - line con 0
        - line vty 0 4
        - login
        - line vty 5 15
        - login
        - end
      show: []
