devices:
  - ip: "192.168.239.134"
    port: 30010
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname R1"
        - "interface e0/0"
        - "ip address 192.168.1.1 255.255.255.0"
        - "no shutdown"
        - "interface e0/1"
        - "ip address 10.10.10.1 255.255.255.252"
        - "no shutdown"
        - "router ospf 100"
        - "network 192.168.1.0 0.0.0.255 area 0"
        - "network 10.10.10.0 0.0.0.3 area 0"
      show:
        - "show ip interface brief"
        - "show ip route"
        - "ping 192.168.1.10 repeat 9"
        - "ping 10.10.10.1 repeat 9"

  - ip: "192.168.239.134"
    port: 30011
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname R2"
        - "interface e0/0"
        - "ip address 10.10.10.2 255.255.255.252"
        - "no shutdown"
        - "interface e0/2"
        - "ip address 192.168.2.1 255.255.255.0"
        - "no shutdown"
        - "interface e0/1"
        - "ip address 10.10.10.5 255.255.255.252"
        - "no shutdown"
        - "router ospf 100"
        - "network 192.168.2.0 0.0.0.255 area 0"
        - "network 10.10.10.0 0.0.0.3 area 0"
        - "network 10.10.10.4 0.0.0.3 area 0"
      show:
        - "show ip interface brief"
        - "show ip route"
        - "ping 192.168.2.10 repeat 9"
        - "ping 192.168.1.10 repeat 9"
  - ip: "192.168.239.134"
    port: 30012
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname R3"
        - "interface e0/0"
        - "ip address 10.10.10.6 255.255.255.252"
        - "no shutdown"
        - "interface e0/1"
        - "ip address 192.168.3.1 255.255.255.0"
        - "no shutdown"
        - "interface e0/2"
        - "ip address 209.65.100.1 255.255.255.252"
        - "no shutdown"
        - "router ospf 100"
        - "network 192.168.3.0 0.0.0.255 area 0"
        - "network 10.10.10.4 0.0.0.3 area 0"
        - "default-information originate" 
        - "ip route 0.0.0.0 0.0.0.0 209.65.100.2"
      show:
        - "show ip interface brief"
        - "show ip route"
        - "ping 192.168.2.10 repeat 9"
        - "ping 192.168.1.10 repeat 9"
  - ip: "192.168.239.134"
    port: 30013
    username: "admin"
    password: "admin"
    device_type: "cisco_ios_telnet"
    commands:
      config:
        - "hostname R4"
        - "interface e0/0"
        - "ip address 209.65.100.2 255.255.255.252"
        - "no shutdown"
        - "interface e0/1"
        - "ip address 8.8.8.1 255.255.255.0"
        - "no shutdown"
        - "ip route 0.0.0.0 0.0.0.0 209.65.100.1"
      show:
        - "show ip interface brief"
        - "show ip route"
        - "ping 192.168.2.10 repeat 9"
        - "ping 192.168.1.10 repeat 9"